[build]
publish = "public"
command = "printenv && hugo --gc --minify"
commandOrigin = "config"

[context.production.environment]
HUGO_VERSION = "0.81.0"

[context.branch-deploy]
PIZZA = "pineapple"

[context.deploy-previews.environment]
command = "hugo --gc --minify"
